# NumPy
NumPy는 고성능 수치 계산을 지원하는 핵심 라이브러리로, Pandas, SciPy, Scikitlearn, TensorFlow 등 많은 라이브러리가 NumPy 배열을 기반으로 작동한다.

In [1]:
import numpy as np

# 배열 생성
- np.array( ) 함수
- np.zeros( ) 함수
- np.ones( ) 함수
- np.full( ) 함수
- np.empty( ) 함수
- np.arange( ) 함수
- np.linspace( ) 함수

In [6]:
# np.array()
x = np.array([1,2,3,4])
print(x)

y = np.array([[1,2,3], [4,5,6]])
print(y)

[1 2 3 4]
[[1 2 3]
 [4 5 6]]


In [25]:
# np.zeros(shape)
x = np.zeros((2,3))
print(x)

[[0. 0. 0.]
 [0. 0. 0.]]


In [18]:
# np.ones(shape)
x = np.ones((2,3))
print(x)

[[1. 1. 1.]
 [1. 1. 1.]]


In [21]:
# np.full(shape, value)
x = np.full((2,2), 7)
print(x)

[[7 7]
 [7 7]]


In [20]:
# np.empty(shape)
# 임의의 값으로 배열 생성
x = np.empty((2,2))
print(x)

[[4.9e-324 9.9e-324]
 [1.5e-323 2.0e-323]]


In [23]:
# np.arange(start, stop, step)
# 지정된 범위와 간격으로 배열 생성
x = np.arange(0,10,2)
print(x)

[0 2 4 6 8]


In [24]:
# np.linspace(start, stop, num)
# 시작값과 끝값 사이를 균등 간격으로 나눈 배열 생성
x = np.linspace(0,1,5)
print(x)

[0.   0.25 0.5  0.75 1.  ]


# 배열의 주요 속성
- shape 속성
- dtype 속성
- size 속성
- ndim 속성
- flat 속성

In [3]:
x = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(x.shape) # 배열의 형태 (n행, n열)
print(x.dtype) # 배열의 데이터 타입
print(x.size) # 배열의 전체 요소 개수
print(x.ndim) # 배열의 차원 수

(3, 3)
int64
9
2


In [5]:
for i in x.flat: # 배열의 모든 요소 값을 반환
    print(i)

1
2
3
4
5
6
7
8
9


# 배열의 데이터 타입
- 기본 데이터 타입
- 데이터 타입 변환 - astype( ) 함수

In [6]:
x = np.array([1.5, 2.3, 3.7])
y = x.astype(np.int32)
print(y)

[1 2 3]


# 배열의 인덱싱
- 기본 인덱싱
- 다차원 배열 인덱싱
- 음수 인덱싱
- 다차원 배열에서의 음수 인덱싱
- Boolean 인덱싱
- 팬시 인덱싱
- 다중 팬시 인덱싱

In [11]:
x = np.array([10,20,30,40,50])
print(x[-1])
print(x[3])
print(x[-3])
print(x[0])

50
40
30
10


In [12]:
x = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(x[1,2])
print(x[0,0])
print(x[-1,-1])

6
1
9


In [14]:
# Booleean 인덱싱 (조건 인덱싱)
x = np.array([10,20,30,40,50])
y = x > 30
print(x[y])

[40 50]


In [15]:
# 팬시(Fancy) 인덱싱 (배열의 특정 인덱스를 리스트나 배열로 지정하여 한 번에 선택)
x = np.array([10,20,30,40,50])
y = [0,2,4]
print(x[y])

[10 30 50]


In [21]:
# 다중 팬시 인덱싱
x = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(x[[0,2], [1,0]])

# 각 배열은 같은 인덱스끼리 짝을 지어 좌표를 만듦
# 쌍 1: (0,1) --> 0행 1열 --> 2
# 쌍 2: (2,0) --> 2행 0열 --> 7

[2 7]


# 배열의 슬라이싱
- 기본 슬라이싱
- 다차원 배열 슬라이싱
- 슬라이싱을 이용한 행/열 선택
- 음수 슬라이싱
- Boolean 배열을 사용한 슬라이싱
- 배열을 사용한 슬라이싱

In [31]:
# 1차원 배열에서는 리스트와 동일하게 동작.
# list[start:stop:step] 기본 값은 start=0, stop=배열 길이, step=1
# start는 포함되지만, stop은 포함되지 않음
x = np.array([10,20,30,40,50])
print(x[1:4]) # x[[1,2,3]]
print(x[:3]) # x[[0,1,2]]
print(x[::2]) # x[[0,2,4]]
print(x[-3:]) # x[[-3,-2,-1]]

[20 30 40]
[10 20 30]
[10 30 50]
[30 40 50]


In [28]:
# 다차원 배열 슬라이싱
x = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(x[0:2, 1:3]) # x[[0,1], [1,2]] -> 0,1행, 1,2열 선택

[[2 3]
 [5 6]]


In [29]:
x = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(x[:, 1])
print(x[1, :])

[2 5 8]
[4 5 6]


In [32]:
# Boolean 배열을 사용한 슬라이싱
x = np.array([10,20,30,40,50])
y = x % 20 ==0  # y는 20의 배수
print(x[y])

[20 40]


In [36]:
x = np.array([10,20,30,40,50])
y = x[1:4]
print(y)

y[0] = 99
print(y)

print(x)

[20 30 40]
[99 30 40]
[10 99 30 40 50]


# 배열의 연산
- 산술 연산
- 지수 연산
- 배열의 비교 연산
- 배열과 스칼라 연산
- 제곱근

Numpy 배열 연산의 주요 특징으로 '브로드캐스팅'이 있다. 두 배열의 크기가 같을 때, 요소별 연산을 자동으로 수행하는 기능이다. 서로 다른 크기의 배열이면 작은 배열의 크기가 자동으로 확장되어 큰 배열과의 연산이 된다.

In [41]:
x = np.array([1,2,3])
y = np.array([4,5,6])

print(x + y) 
print(x + 2)
print(x - y)
print(x * y)
print(x * 3)
print(x / y)
print(x ** 2) # 제곱

[5 7 9]
[3 4 5]
[-3 -3 -3]
[ 4 10 18]
[3 6 9]
[0.25 0.4  0.5 ]
[1 4 9]


In [40]:
x = np.array([1,2,3])
y = np.array([3,2,1])

print(x>y)
print(x==y)

[False False  True]
[False  True False]


In [42]:
x = np.array([1,4,9])
print(np.sqrt(x))

[1. 2. 3.]


# 배열 비교
- 요소별 비교
- 배열 간 비교
- np.all( )
- np.any( )
- np.array_equal( )

In [43]:
x = np.array([10,20,30,40,50])
print(x>30)

y = np.array([[1,2,3], [4,5,6]])
print(y>3)

[False False False  True  True]
[[False False False]
 [ True  True  True]]


In [44]:
x = np.array([1,2,3])
y = np.array([4,5,6])
z = np.array([[1,2,3], [4,5,6], [3,2,1]])

print(x >= y)
print(x >= z)

[False False False]
[[ True  True  True]
 [False False False]
 [False  True  True]]


In [45]:
x = np.array([True, False, True])

print(np.all(x)) # 모든 요소가 True인지
print(np.any(x)) # 하나 이상의 요소가 True인지

False
True


In [46]:
# np.array_equal() : 두 배열의 크기, 요소 모두 동일한지
x = np.array([1,2,3])
y = np.array([1,2,3])
z = np.array([1,2,4])

print(np.array_equal(x,y))
print(np.array_equal(x,z))

True
False


# 배열 병합

In [49]:
x = np.array([[1,2], [3,4]])
y = np.array([[5,6], [7,8]])

print(np.concatenate((x,y), axis=0)) # 행 기준 결합
print(np.concatenate((x,y), axis=1)) # 열 기준 결합

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]


# 배열 정렬
- 1차원 배열 정렬
- 다차원 배열 정렬
- 내림차순 정렬
- 원본 배열 정렬 - ndarray.sort( )
- 다중 조건 정렬 - np.lexsort( )

In [50]:
x = np.array([3,1,2,5,4])
print(np.sort(x)) # 오름차순
print(np.sort(x)[::-1]) # 내림차순

[1 2 3 4 5]
[5 4 3 2 1]


In [51]:
a = np.array([[3,1,2], [9,8,7]])
print(a)
print(np.sort(a, axis=0)) # 각 열 내에서 정렬
print(np.sort(a, axis=1)) # 각 행 내에서 정렬
print(np.sort(a, axis=None)) # 1차원으로 평탄화 후 정렬

[[3 1 2]
 [9 8 7]]
[[3 1 2]
 [9 8 7]]
[[1 2 3]
 [7 8 9]]
[1 2 3 7 8 9]


In [52]:
# 2차원 배열을 내림차순으로 정렬
x = np.array([[3,1,4], [1,5,9], [2,6,5]])
print(np.sort(x)[:, ::-1]) # 행 기준 내림차순 정렬 -> 열 기준 오름차순 정렬 -> 전체 역순으로 뒤집음
print(np.sort(x, axis=0)[::-1, :]) # 열 기준 내림차순 정렬 -> 열 기준 오름차순 정렬 -> 전체 역순으로 뒤집음

[[4 3 1]
 [9 5 1]
 [6 5 2]]
[[3 6 9]
 [2 5 5]
 [1 1 4]]


In [53]:
# ndarray 객체의 sort() 함수는 원본 배열을 직접 정렬한다. np.sort()는 원본 배열은 변경되지 않는다.
x = np.array([3, 1, 2, 5, 4]) 
x.sort() 
print(x)
x = x[::-1] 
print(x)

y = np.array([[3, 1, 4], [1, 5, 9]]) 
y.sort(axis=1) # 각 행 기준으로 정렬
print(y)
y.sort(axis=0) # 각 열 기준으로 정렬
print(y)

[1 2 3 4 5]
[5 4 3 2 1]
[[1 3 4]
 [1 5 9]]
[[1 3 4]
 [1 5 9]]


In [57]:
# 다중 조건 정렬 - np.lexsort()
x = np.array([25, 30, 22, 24])
y = np.array(["철수", "영희", "민수", "영희"])
z = np.lexsort((x, y)) # (기준2,기준1)
print(z) # y를 우선 정렬하고, 동일한 값에 대해서는 x로 정렬. 정렬된 인덱스를 저장.
print(x[z]) 
print(y[z])

[2 3 1 0]
[22 24 30 25]
['민수' '영희' '영희' '철수']


# 배열 필터링
- 기본 필터링
- 다차원 배열 필터링
- np.where( )를 사용한 필터링
- 마스크 배열을 이용한 필터링 - ma.array( )
- 복합 조건을 사용한 필터링
- np.extract( )를 사용한 조건 기반 추출

In [59]:
x = np.array([1,2,3,4,5])
print(x>3)
print(x[x>3])

[False False False  True  True]
[4 5]


In [61]:
x = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(x[x>5])

[6 7 8 9]


In [64]:
# np.where(조건, x, y)
# x : 조건이 True인 경우 반환할 값
# y : 조건이 False인 경우 반환할 값
x1 = np.array([10,20,30,40,50])
y1 = np.where(x1>25, x1, -1)
print(y1)

x2 = np.array([[1,2,3], [4,5,6], [7,8,9]])
y2 = np.where(x2 % 2 ==0, x2, -1)
print(y2)

print(np.where(x1 < 30)) # 조건을 만족하는 요소의 인덱스를 반환

[-1 -1 30 40 50]
[[-1  2 -1]
 [ 4 -1  6]
 [-1  8 -1]]
(array([0, 1]),)


In [66]:
# ma.array() 함수는 특정 조건에 맞지 않는 값을 마스킹하여 결측치 또는 불필요한 값을 제외하거나 숨길 수 있게 함.
x = np.array([1,2,3,4,5])
y = x % 2 ==1
print(y)

z = np.ma.array(x, mask=y)
print(z)

print(np.ma.sum(z)) # 마스크된 배열의 합계 (2+4)

[ True False  True False  True]
[-- 2 -- 4 --]
6


In [67]:
x = np.array([10, 20, 30, 40, 50, 60, 70, 80]) 
y = np.array([15, 22, 35, 45, 55, 65, 75, 85]) 

cond1 = x > 30 
print(cond1)

cond2 = y < 50 
print(cond2)

print(x[cond1 & cond2]) # and
print(x[cond1 | cond2]) # or
print(x[~cond2]) # not

[False False False  True  True  True  True  True]
[ True  True  True  True False False False False]
[40]
[10 20 30 40 50 60 70 80]
[50 60 70 80]


In [68]:
x = np.array([10,20,30,40,50])
print(np.extract(x>25, x))

[30 40 50]


# 배열의 통계
- 최솟값 - np.min( )
- 최댓값 - np.max( )
- 데이터 범위 - np.ptp( )
- 합계(Sum) - np.sum( )
- 평균(Mean) - np.mean( )
- 중위수(Median) - np.median( )
- 분산(Variance) - np.var( )
- 표준편차(Standard Deviation) - np.std( )
- 사분위수(Quantiles) - np.percentile( )

In [70]:
x = np.array([1,2,3,4,5])
print(np.min(x))
print(np.max(x))
print(np.ptp(x)) # peak to peak(최댓값과 최솟값의 차이, 데이터의 범위)
print(np.sum(x))
print(np.mean(x))
print(np.median(x))
print(np.var(x))
print(np.std(x))
print(np.percentile(x, 25))
print(np.percentile(x, 75))

1
5
4
15
3.0
3.0
2.0
1.4142135623730951
2.0
4.0


## Review

In [74]:
print(np.array([5,10,15]))

[ 5 10 15]


In [88]:
x = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(x.ndim)

2


In [78]:
x = np.ones((3,3))
print(x)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [79]:
x = np.array([2,4,6,8,10])
cond = x > 5
print(x[cond])

[ 6  8 10]


In [80]:
x = np.array([1,2,3])
y = np.array([4,5,6])
print(x+y)

[5 7 9]


In [91]:
x = np.array([1,2,3,4,5,6])
print(x.reshape(2,3))

[[1 2 3]
 [4 5 6]]


In [81]:
x = np.array([10,20,30,40,50])
y = x % 20 ==0
print(x[y])

[20 40]


In [85]:
x = np.array([[3,2,1], [6,5,4]])
print(np.sort(x, axis=0))
print(np.sort(x, axis=1))

[[3 2 1]
 [6 5 4]]
[[1 2 3]
 [4 5 6]]
